# Generated by Django 2.1.5 on 2019-01-21 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('receipt_code', models.CharField(max_length=64, unique=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoeBox',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ShoeBoxes',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('x1', models.IntegerField(blank=True, null=True)),
                ('y1', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptLabel',
            fields=[
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='labels', serialize=False, to='labeler.Receipt')),
                ('merchant_present', models.BooleanField(default=False)),
                ('merchant_missing', models.BooleanField(default=False)),
                ('merchant_broken', models.BooleanField(default=False)),
                ('amount_present', models.BooleanField(default=False)),
                ('amount_missing', models.BooleanField(default=False)),
                ('amount_broken', models.BooleanField(default=False)),
                ('sub_total_present', models.BooleanField(default=False)),
                ('sub_total_missing', models.BooleanField(default=False)),
                ('sub_total_broken', models.BooleanField(default=False)),
                ('tax_present', models.BooleanField(default=False)),
                ('tax_missing', models.BooleanField(default=False)),
                ('tax_broken', models.BooleanField(default=False)),
                ('date_present', models.BooleanField(default=False)),
                ('date_missing', models.BooleanField(default=False)),
                ('date_broken', models.BooleanField(default=False)),
                ('date_upd', models.DateTimeField(auto_now=True, null=True)),
                ('user_upd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WordLabel',
            fields=[
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='labels', serialize=False, to='labeler.Word')),
                ('merchant', models.BooleanField(default=False)),
                ('merchant_rank', models.IntegerField(default=0)),
                ('amount', models.BooleanField(default=False)),
                ('amount_rank', models.IntegerField(default=0)),
                ('sub_total', models.BooleanField(default=False)),
                ('sub_total_rank', models.IntegerField(default=0)),
                ('tax', models.BooleanField(default=False)),
                ('tax_rank', models.IntegerField(default=0)),
                ('date', models.BooleanField(default=False)),
                ('date_rank', models.IntegerField(default=0)),
                ('date_upd', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='words', to='labeler.Receipt'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='shoebox',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receipts', to='labeler.ShoeBox'),
        ),
    ]
